# example docker-compose configuration file for using mkodockx/docker-clamav
version: '3.7'

services:
  av:
    #debian: image: mkodockx/docker-clamav
    #image: mkodockx/docker-clamav:alpine
    build: 
      dockerfile: ./Dockerfile
      context: ./clamav-icap-docker
    container_name: alfresco-clamav
    restart: unless-stopped
    ports:
        - published: 3310
          target: 3310
    volumes:
      - clam:/var/lib/clamav

volumes:
  clam:

networks:
  outpost_network:
    external: true
  
