# Alfresco Security and Protection Services (ClamAV+ICAP)
version: '3.7'

services:
  alfviral-clamav-icap:
    build: 
      dockerfile: ./Dockerfile
      context: ./build
    restart: unless-stopped
    ports:
        - published: 3310
          target: 3310
    volumes:
      - clam:/var/lib/clamav
      - alfviral-platform-acs-volume:/usr/local/tomcat/alf_data

volumes:
  clam:
    external: false
  alfviral-platform-acs-volume:
    external: true

networks:
  outpost_network:
    external: true
  
