# example docker-compose configuration file for using mkodockx/docker-clamav
version: '3.7'

services:
  av:
    build: 
      dockerfile: ./Dockerfile
      context: ./build
    container_name: alfresco-security-protection-services
    restart: unless-stopped
    ports:
        - published: 3310
          target: 3310
    volumes:
      - clam:/var/lib/clamav

volumes:
  clam:

networks:
  outpost_network:
    external: true
  
