name: Maven Package and Release

on:
  push:
    branches:
      - master
      - 'edu-sharing-*'
    tags:
      - '*'  # Triggers releases for tags

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Dynamic module builds
      - name: Build alfviral-platform module
        if: startsWith(github.ref_name, 'edu-sharing-') || github.ref_name == 'master'
        run: mvn -B package --file alfviral-platform/pom.xml
      
      - name: Build alfviral-share module
        if: startsWith(github.ref_name, 'edu-sharing-') || github.ref_name == 'master'
        run: mvn -B package --file alfviral-share/pom.xml

      # Archive artifacts using v4
      - name: Archive alfviral-platform artifacts (.jar and .amp)
        if: startsWith(github.ref_name, 'edu-sharing-') || github.ref_name == 'master'
        uses: actions/upload-artifact@v4
        with:
          name: alfviral-platform
          path: |
            alfviral-platform/target/alfviral-platform-*.jar
            alfviral-platform/target/alfviral-platform-*.amp
          
      - name: Archive alfviral-share artifacts (.jar and .amp)
        if: startsWith(github.ref_name, 'edu-sharing-') || github.ref_name == 'master'
        uses: actions/upload-artifact@v4
        with:
          name: alfviral-share
          path: |
            alfviral-share/target/alfviral-share-*.jar
            alfviral-share/target/alfviral-share-*.amp

  release:
    if: startsWith(github.ref, 'refs/tags/') && github.ref_name == 'master'
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Download alfviral-platform artifact
        uses: actions/download-artifact@v4
        with:
          name: alfviral-platform

      - name: Download alfviral-share artifact
        uses: actions/download-artifact@v4
        with:
          name: alfviral-share

      - name: Create GitHub Release with Auto-generated Release Notes
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          generateReleaseNotes: true
          name: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      # Upload artifacts as release assets using v4
      - name: Upload alfviral-platform assets (.jar and .amp)
        uses: actions/upload-release-asset@v4
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: alfviral-platform/target/alfviral-platform-*.jar
          asset_name: alfviral-platform-${{ github.ref_name }}.jar
          asset_content_type: application/java-archive

      - name: Upload alfviral-share assets (.jar and .amp)
        uses: actions/upload-release-asset@v4
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: alfviral-share/target/alfviral-share-*.jar
          asset_name: alfviral-share-${{ github.ref_name }}.jar
          asset_content_type: application/java-archive

      - name: Upload alfviral-platform AMP asset
        uses: actions/upload-release-asset@v4
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: alfviral-platform/target/alfviral-platform-*.amp
          asset_name: alfviral-platform-${{ github.ref_name }}.amp
          asset_content_type: application/zip

      - name: Upload alfviral-share AMP asset
        uses: actions/upload-release-asset@v4
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: alfviral-share/target/alfviral-share-*.amp
          asset_name: alfviral-share-${{ github.ref_name }}.amp
          asset_content_type: application/zip
